package com.cpp.modle;
// Generated 2017-4-1 8:59:00 by Hibernate Tools 3.2.2.GA

import java.util.Date;

/**
 * Bankcard generated by hbm2java
 */
public class Bankcard implements java.io.Serializable {

	private int BId;
	////增加Employee对象
	private Employee employee;
	private String BNumber;
	private Date BTime;	
	
	
	public Bankcard() {
	}

	public Bankcard(int BId) {
		this.BId = BId;
	}

	public Bankcard(int BId, Employee employee, String BNumber, Date BTime) {
		this.BId = BId;
		this.employee = employee;
		this.BNumber = BNumber;
		this.BTime = BTime;
	}

	public int getBId() {
		return this.BId;
	}

	public void setBId(int BId) {
		this.BId = BId;
	}

	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	public String getBNumber() {
		return this.BNumber;
	}

	public void setBNumber(String BNumber) {
		this.BNumber = BNumber;
	}

	public Date getBTime() {
		return this.BTime;
	}

	public void setBTime(Date BTime) {
		this.BTime = BTime;
	}

}
