package com.cpp.modle;
// Generated 2017-3-27 11:24:19 by Hibernate Tools 3.2.2.GA

/**
 * Elector generated by hbm2java
 */
public class Elector implements java.io.Serializable {

	private String name;
	private String password;
	private String count;
	private String flag;

	public Elector() {
	}

	public Elector(String name, String password) {
		this.name = name;
		this.password = password;
	}

	public Elector(String name, String password, String count, String flag) {
		this.name = name;
		this.password = password;
		this.count = count;
		this.flag = flag;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getCount() {
		return this.count;
	}

	public void setCount(String count) {
		this.count = count;
	}

	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	@Override
	public String toString() {
		return "Elector [name=" + name + ", password=" + password + ", count=" + count + ", flag=" + flag + "]";
	}
	
	

}
